# Generated by Django 3.1.3 on 2020-12-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=200)),
                ('evolution_level', models.IntegerField(blank=True, default='-', null=True)),
                ('next_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.pokemonspecie')),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_nickname', models.CharField(max_length=200)),
                ('pokemon_level', models.IntegerField(default=0)),
                ('pokemon_trainer', models.CharField(max_length=200)),
                ('pokemon_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pokemonspecie')),
            ],
        ),
    ]
