# Generated by Django 3.1.3 on 2020-12-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonspecie',
            name='pokemon_type',
        ),
        migrations.AddField(
            model_name='pokemonspecie',
            name='pokemon_type',
            field=models.ManyToManyField(to='my_app.PokemonType'),
        ),
    ]
