# Generated by Django 3.1.3 on 2020-12-02 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20201201_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pokemon'),
        ),
    ]
