# Generated by Django 3.1.3 on 2020-12-02 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20201202_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pokemon')),
            ],
        ),
    ]
