# Generated by Django 3.1.3 on 2020-12-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_name',
            field=models.CharField(max_length=200),
        ),
    ]
